### ISSUE TITLE
TriadBuddy listed twice in plugin list

### ISSUE THREAD

**Issue by steponmepls** [MgAl2O4/FFTriadBuddyDalamud#1]
I don't know if this is intended so I'm reporting it here

![image](https://user-images.githubusercontent.com/63500907/130611134-91115f37-6475-4464-8554-d96b0b40c743.png)

**Comment by steponmepls** [comment]
Only the first Install button appears to work. Second fails with an error prompt

**Comment by MgAl2O4** [comment]
1.0.0.0 is for api3 (current live version)
1.0.0.2 for api4 (test version, new big thing, etc)

Are you on test? I was hoping that Dalamud will filter out unavailable stuff automatically.

**Comment by steponmepls** [comment]
No I'm not. I'll try enabling testing and see if it lets me install the 1.0.0.2 version

**Comment by steponmepls** [comment]
No luck. It just fails. I don't know anything about plugins but maybe you have to toggle this on for testing in `pluginmaster.json` `"IsTestingExclusive": false`

![image](https://user-images.githubusercontent.com/63500907/130611723-d09cec25-b788-4ee7-a734-48609912202e.png)

**Comment by MgAl2O4** [comment]
I think I finally got the flags correct. 
API 4 version will appear only when plugin testing is enabled and is clearly marked as such. Works in both live & api 4 versions (%appdata%\XIVLauncher\dalamudConfig.json - DoDalamudTest = true)

![snap](https://user-images.githubusercontent.com/51430403/130627475-06229e6b-a264-4c67-9a9e-bb4d389d17c5.PNG)

**Comment by steponmepls** [comment]
Yes the plugin is correctly hidden now when testing is toggled off but the install keeps failing on my end but I think that's off-topic ins this Issue

**Comment by MgAl2O4** [comment]
![snap](https://user-images.githubusercontent.com/51430403/130628472-a180a044-7b9d-488c-b18d-4af794e5487a.PNG)

Is it still failing when installing 1.0.0.0 ?

**Comment by steponmepls** [comment]
Yes. The stable version is installed properly but the testing one always fails

**Comment by MgAl2O4** [comment]
You need dalamud testing version (api 4, check syntax for config file) to install that.
There's no way to hide it in currently live (api 3) as far as i know, sorry.

**Comment by steponmepls** [comment]
I just wanted to mention the plugin is listed twice again but only in the `Installed Plugins` tab (not in the `Available Plugins` list). I do have testing disabled but I don't know if they are supposed to both show at the same time when installed. Can't tell if there's an issue with the repo json file so yeah reporting this just in case it's an error

![image](https://user-images.githubusercontent.com/63500907/131377818-4fe0abfd-8077-4814-bcc8-b7238df61d65.png)

**Comment by MgAl2O4** [comment]
It's just plugin installer getting confused about versions.
- latest api3 (live) build: 1.0.2.0
- latest api4 (dalamud staging) build: 1.2.0.1

I'll ask on discord for help - it's either issue with entries in my pluginmaster.json or with plugin installer. Sorry for confusion.
If it suddenly starts to load multiple versions at the same time (hm, maybe 2 windows opened on /triadbuddy command ?) 
- close game first
- go to "%appdata%\XIVLauncher\installedPlugins\" 
- remove all folders for TriadBuddy
- install in game again :<
