### ISSUE TITLE
Lewena not removed from NPC list once beaten

### ISSUE THREAD

**Issue by ibigfire** [MgAl2O4/FFTriadBuddyDalamud#10]
Even after she's been beaten Lewena does not get removed from the list after "Hide beaten once" is ticked.

Thanks for all the work put into this.

**Comment by MgAl2O4** [comment]
Hm, it's based on stuff that is supposed to be working - counting npcs for achievement, but i didn't really verify it myself. Yet. Will investigate, either it's working and description doesn't really match functionality (beaten once vs marked for achievement) OR i messed it up.

**Comment by ibigfire** [comment]
For what it's worth every other NPC I've checked so far seems to be working as far as I can tell, so I'm unsure what's special about her specifically.

**Comment by MgAl2O4** [comment]
Turns out that Lewena doesn't count for achievement. Didn't know that :)

**Comment by MgAl2O4** [comment]
Fixed in 1.0.2.9 (api3/live) and 1.2.0.7 (api4)
All npcs excluded from achievement tracker will be hidden when "Hide beaten once" is checked (leaving checkbox description as it is, localization updates are annoying)
