### ISSUE TITLE
Missing NPC ? Indolent Imperial

### ISSUE THREAD

**Issue by Digawen** [MgAl2O4/FFTriadBuddyDalamud#11]
Mor Dhona (X:11.9 Y:17.4) 

I just wanted to ask if this is intentional or if the NPC was forgotten?

**Comment by MgAl2O4** [comment]
Not sure what you mean, NPC is definitely on the lists when I'm checking card collection.

If there is a problem with detecting NPC during minigame, can you send me log file? (%appdata%\xivlauncher\dalamud.log) It's supposed to log all errors with matching names, so hopefully will have something to fix.

(can't check myself right now)

**Comment by MgAl2O4** [comment]
Made a run for it on test account, lol - works for me. Will need log / screenshot to verify
![test](https://user-images.githubusercontent.com/51430403/134081683-77053692-df24-414e-b486-ab36a5f81abe.png)

**Comment by Digawen** [comment]
2021-09-20 23:02:32.694 +02:00 [ERR] [TriadBuddy] failed to match npc: Arbeitsfauler Garlear

this is the only error message in the log.
Maybe because i play in german?

**Comment by MgAl2O4** [comment]
Fixed in 1.0.2.10 (api3/live) and 1.2.0.8 (api4)
