### ISSUE TITLE
Used the Optimizer - Audio Out of Sync

### ISSUE THREAD

**Issue by HonestYeti** [MgAl2O4/FFTriadBuddyDalamud#13]
After using the optimizer, the game audio is out of sync about 2-3 seconds. Tried to restart game and pc and still out of sync. Tried to disable plugin and no luck.

**Comment by MgAl2O4** [comment]
That's pretty weird. Which plugin version are you using? Does it happen all the time? How long did the optimizer ran for / how badly it brick your machine? This process is pretty CPU intensive, but should leave some of processing power to game threads.

I can't repro anything like that, sounds for interacting with npcs are coming up in sync with ui popups.

**Comment by HonestYeti** [comment]
I'm using the one for Dalamud plugin; XIVLauncher ver6.0.6.0. Looking at the instructions I'm using it through the experimental link. Running the optimizer, on average is just under a minute but at times as long as a minute and a half. Can definitely notice the CPU intensity as the game will stutter and sometimes freeze for a moment or two. Sounds like it just may be my CPU is not strong enough to run the game and the optimizer and causing the out of sync. One thing I still need to test is if i can get the in-game audio to fix without using XIVLauncher. For my CPU, it is a Inte I5-6600K.

**Comment by HonestYeti** [comment]
Alright so figured it out, the dsync was caused by my audio source afterward. Once trying a different one, it's no as it should be. Just strange how that happened.

**Comment by MgAl2O4** [comment]
Heh, glad you've got it figured out then. I'll add a simple mode for optimizer - blind pick from top of card pools instead of checking various deck combos. Won't be as good, but then again, entire optimizer feature is of ekhm.. questionable accuracy. In match solver will make it work anyway.
