### ISSUE TITLE
Support for none standard Dalamud UI Scale

### ISSUE THREAD

**Issue by DenL** [MgAl2O4/FFTriadBuddyDalamud#14]
On higher resolutions some users might increase the UI scale to make text readable, which could cause the card collection overlay to look like this: (1.3 scale)
![image](https://user-images.githubusercontent.com/5632219/135346295-3b334a6b-d9c9-4f30-8ca3-80d93bec417f.png)

Would be great if actual size could adjust based on dalamud ui scale, thanks!

**Comment by MgAl2O4** [comment]
Didn't know it's a thing.
Fixed in 1.2.0.12
