### ISSUE TITLE
Feature Request: Fight and drop records

### ISSUE THREAD

**Issue by Noshei** [MgAl2O4/FFTriadBuddyDalamud#15]
Would be really nice to have this plugin log wins/losses/draws per NPC and the numbers of drops per card for each NPC.

**Comment by MgAl2O4** [comment]
What's the purpose of seeing all the stats? Estimating avg gain MGP per fight / finding best npc to farm on? 

My only problem is putting deck (and sometimes region rules) depended values in stored-forever aggregates. Maybe it can be rolling window of X last fights to combat that?

**Comment by Noshei** [comment]
I hadn't even thought of the finding the best NPC to farm bit, but that would certainly be useful.

For me it was more about getting the data so it can easily be shared on places like https://arrtripletriad.com/, so your idea of X last fights would work for this.

**Comment by MgAl2O4** [comment]
Added in 1.2.1.0 (api4) and 1.0.2.15 (api3/live)
