### ISSUE TITLE
Reverse Ascension optimization seems wrong

### ISSUE THREAD

**Issue by retep998** [MgAl2O4/FFTriadBuddyDalamud#16]
When I optimize a deck for Gyoei who has rules of Ascension Plus and Reverse, it insists on optimizing to a deck where every card has a type other than none, even though that will *raise* the card's value making it easier to flip. The deck it generates also ends up having a lower win chance than my normal reverse deck where all the cards have a type of none.

**Comment by retep998** [comment]
The same also applies to Reverse Descension (Redard being an example NPC), where it avoids cards with types, even though having a full set of matching types is clearly better in that case.

**Comment by MgAl2O4** [comment]
Changed in 1.2.1.0 (api4) and 1.0.2.15 (api3/live)
