### ISSUE TITLE
Endwalker Support

### ISSUE THREAD

**Issue by xnuken** [MgAl2O4/FFTriadBuddyDalamud#20]
Does not work on Endwalker npc's

**Comment by MgAl2O4** [comment]
Just played a round with Aiglephine and it works fine for me.

1. Which plugin version are you on? (expected: 1.4.0.0)
2. Is it failing for all new npcs or just some?
3. What are the reported card/npc numbers in plugin's status window (/triadbuddy) (expected: 347 cards, 108 npcs)
4. What is your client language? It's matching stuff based on name so it's possible that some language data is broken.

**Comment by MgAl2O4** [comment]
Just in case: Dalamud is currently disabled and access to plugins requires a few additional steps. Please refer to their Discord server for more information.

If tool shows up on old areas correctly and doesn't work on new ones, please answer questions from list above. Can't help without additional info.

**Comment by MgAl2O4** [comment]
closing for now due to lack of repro / additional info.
