### ISSUE TITLE
Deck Optimizer window constantly expands its size rightward when open

### ISSUE THREAD

**Issue by ryankhart** [MgAl2O4/FFTriadBuddyDalamud#23]
Is this just me or is everyone else experiencing this bug in 6.11?

**Comment by MgAl2O4** [comment]
Can't repro. 
Sounds like auto resize fighting with too big? overlapping? content: may depend on your exact drawing settings, like font type, size, texture resolution, etc.

1. Close game, edit %appdata%\xivlauncher\dalamudUI.ini and remove section for "[Window][Deck Optimizer]", restart game, check.
2. If didn't help, please provide more details from Dalamud Settings > Look & Feel that may be relevant here. Try with default ones?

**Comment by ryankhart** [comment]
It turns out that it was an incompatibility with the 3rd party Dalamud style called "Dark Theme (tenshiHaru)" that I had downloaded from the Discord #preset-sharing channel.

It's obviously a bug somewhere, but I'd argue that it should even be a possibility in the style editor to cause this issue. So, if I end up pinpointing the exact cause, I'll just open up a new issue with Dalamud core, probably.

**Comment by SelfAfflicted** [comment]
I've been having this same issue when using a custom style, and I've determined if the the first variable of WindowPadding is below 5, the optimizer and main window for triadbuddy will continuously expand, immediately upon changing this variable to 5 or higher, the windows will retract to their default sizes.
