### ISSUE TITLE
Deck optimization seems to have some minor issues

### ISSUE THREAD

**Issue by mikeshardmind** [MgAl2O4/FFTriadBuddyDalamud#27]
![image](https://user-images.githubusercontent.com/22035876/212499962-100aa02a-9433-473e-8e22-0046332b2dca.png)

I haven't had a chance to dig into what's causing this yet, it may be upstream or in the use of the upstream code, or just a display issue of existing decks (shared being from triad-shared submodule)

It's not a big deal, it seems to only happen with decks that are rated similarly and highly (lewena's deck is notoriously strong, decks available in this selection reaching 45% is a lot) Which leads me to believe it involves upstream code logic and a non-exhaustive deck search.

I'll see if I can spend time looking at this in the future.

Note: if it is just a non-exhaustive search finding one of multiple peaks, it might be worth making sure that there is a way to ensure currently saved decks are checked for best performance and compared against the solver's result.

**Comment by MgAl2O4** [comment]
It's part of design, more details mentioned in:
https://github.com/MgAl2O4/FFTriadBuddy/issues/75 (this exact case)
https://github.com/MgAl2O4/FFTriadBuddy/issues/60 (more detailed)

Desktop app masks that issue with what you're suggesting - reusing already calculated values of built decks. I can't remember if I made plugin version do the same. Apparently not and it's a source of mismatch, will get it fixed soonish.

**Comment by mikeshardmind** [comment]
Oh, I should have searched issues upstream as well. Thanks for the info as well as the work you've put into this.
