### ISSUE TITLE
[Suggestion] Dim cards that doesnt match card search in the Edit Deck

### ISSUE THREAD

**Issue by imgidedin** [MgAl2O4/FFTriadBuddyDalamud#29]
Would be great if we could type a card name, like, Ultima Weapon, for example, and it would dim all other cards but the few cards that matches the list that is filtered, kinda like the Optimize Deck does when it is open and you go edit a deck. Is that possible?

If not, is there a way to make it so when we click a card that we search for, it takes us to the card? Tried that and it just takes us to the first card on a random page once and then nothing more after.

**Comment by MgAl2O4** [comment]
Fixed in 1.8.0.2
