### ISSUE TITLE
[Suggestion] An option to turn off card flicker in Card Deck Edit

### ISSUE THREAD

**Issue by Rueby** [MgAl2O4/FFTriadBuddyDalamud#32]
Hello! I've been doing TT alot lately and been using the deck optimizer pretty frequently. 

I couldn't help but notice how quickly the highlighted cards flicker pretty frequently causing me to have to strain to look at it. I think if the highlight is static it'd compliment the dimmed effect the other cards have during selection. 

I apologize if this seems very specific, I struggle with things that flash/flicker constantly and find it hard/painful to look at! Thank you so much for the amazing plugin.

**Comment by MgAl2O4** [comment]
Good idea, changed in 1.9.1
