### ISSUE TITLE
Deck optimizer window keeps growing in width

### ISSUE THREAD

**Issue by stephendrew** [MgAl2O4/FFTriadBuddyDalamud#35]
As per the title, when the deck optimizer is open, it keeps growing uncontrollably wider.
This stops when it is minimized.
![image](https://github.com/user-attachments/assets/9bc41400-40cb-4ab4-b454-361d2b964526)
![image](https://github.com/user-attachments/assets/7fdc7b1f-e68b-43ae-8577-ce3e72916f96)
![image](https://github.com/user-attachments/assets/ffe304aa-7720-426f-9bc1-80b0262bd0fb)

**Comment by MgAl2O4** [comment]
fixed in 1.10.0.1
