### ISSUE TITLE
FailedToParseNpc when playing NPCs with spaces in name (German localisation)

### ISSUE THREAD

**Issue by tschoerk** [MgAl2O4/FFTriadBuddyDalamud#5]
When playing a game in the German localisation vs. an NPC which has a space in their name, for example Stolzer Hirsch der Neureiche (Prideful Stag) or Flichoirel der Höchnäsige (Flichoirel the Lordling) the status says FailedToParseNpc.

In the prepartion screen itself, the NPC is succesfully recognized:
Status: Minigame not active
Prep.NPC: Stolzer Hirsch der Neureiche
Prep.Rules: Plus

Also the deck selection shows the approximate win percentages.
 
Only after selecting a deck and the game starts it switches to:
Status: FailedtoParseNPC
Solver.NPC: --
Solver.Move: --

This only seems to happen with NPCs which have space in their name, since all others works just fine. Didn't test if this is a localisation problem or arises with every language version.

**Comment by MgAl2O4** [comment]
Hm, checked on tutorial NPCs with German client (Jonas Pik, etc), but it seems to work fine. Maybe those two from battle hall are more special, will see.

**Comment by tschoerk** [comment]
You're right the space isn't the problem apparantly. NPCs like Sezul Totoloq work as well. 
Outside the battle hall it only seems to also happen with (can only test ARR npcs, haven't played further) Arbeitsfauler Garlear (Indolent Imperial)

**Comment by MgAl2O4** [comment]
Ah, I see. I'm reading game data wrong, particular npc name ends up being "Flichoirel [t] Hochnäsig[a]". You're using api3 build (live Dalamud release), right?

**Comment by tschoerk** [comment]
Yes I'm using the stable, live api3 version (Dalamud vD5.2.7.0).
