### ISSUE TITLE
[Bug] Optimizer make my cards dark

### ISSUE THREAD

**Issue by Lanselotto** [MgAl2O4/FFTriadBuddyDalamud#6]
When optimizer is open, ALL my cards are dark. I suppose it should higlight the right ones but it doesnt.

**Comment by MgAl2O4** [comment]
Would you mind sending log (%appdata%\XIVLauncher\dalamud.log) ?
It's supposed to match by texture name and if it fails, it should log errors about it.

**Comment by Lanselotto** [comment]
little edit, if i optimize while im creating a deck, it works fine. The problems appear when i optimize and then i open deck creation and try to make a deck. Nothing in xllog. Is this as intended?

**Comment by MgAl2O4** [comment]
Ah, I see. Yup, it's a bug, highlights don't appear until you press optimize. Opening that window without any actions is just dark cards. Nice find!

**Comment by Lanselotto** [comment]
Nice. Sorry if i ask here, but is the version on main repo updated? cause i see that you made a custom repo, should i use that or can i use the main repo version?

**Comment by MgAl2O4** [comment]
Both are kept up to date, the only difference is api version.
- main Dalamud plugin repo = api4 only (could lag behind a day as it goes through approval process)
- this custom repo path = api3 only

Once Dalamud is live with 6.0 / api4, this custom repo will be retired.

**Comment by Lanselotto** [comment]
oh, ok, thanks!

**Comment by MgAl2O4** [comment]
fixed in 1.2.0.4 (api4) / 1.0.2.4 (api3)
