### ISSUE TITLE
The plugin does not remove 2B from the list even after checking the box "not owned only"

### ISSUE THREAD

**Issue by rrbailey89** [MgAl2O4/FFTriadBuddyDalamud#9]
The plugin version does not remove 2B from the list even after checking the box "not owned only"

**Comment by MgAl2O4** [comment]
Hm, it was being fixed recently - what version number are you on?

**Comment by MgAl2O4** [comment]
Actually, never mind, I forgot to move fix to api3 build. 
Fixed in 1.0.2.8 (api3/live) and 1.2.0.5 (api4)

**Comment by rrbailey89** [comment]
Ahh I see. Im on 1.0.2.7 that would explain it.
